version: "3"

dotenv: 
- .env

vars:
  TITLE: The Seven Hills of Rome
  HELM_CHART: locator-api
  SKU: Standard_D4ads_v5
  DEFAULT_REGION: canadacentral
  APP_URL: https://locator-api.{{.DEFAULT_DOMAIN}} #DEFAULT_DOMAIN is defined in the .env file
  COUNT: 3
  NAMESPACE: rome 
  OPENAI_DEPLOYMENT_NAME: gpt-4.1
  OPENAI_API_VERSION: 2024-12-01-preview
  
includes:
  local:
    taskfile: ./infrastructure/local/Taskfile.local.yaml
    internal: false
    dir: ./infrastructure/local/

  azure:
    taskfile: ./infrastructure/azure/Taskfile.aks.yaml
    internal: false
    dir: ./infrastructure/azure/

tasks:  
  default:
    cmds:
      - task --list
