version: "3"

dotenv: 
  - .env

vars:
  TITLE: The Seven Hills of Rome
  HELM_CHART: locator-api
  SKU: Standard_D4ads_v5
  DEFAULT_REGION: canadacentral
  DEFAULT_DOMAIN: bjdazure.tech
  APP_URL: https://locator-api.{{.DEFAULT_DOMAIN}}
  COUNT: 2
  NAMESPACE: rome 

includes:
  local:
    taskfile: ./infrastructure/local/Taskfile.local.yaml
    internal: false
    dir: ./infrastructure/local/

  kubernetes:
    taskfile: ./infrastructure/kubernetes/Taskfile.aks.yaml
    internal: false
    dir: ./infrastructure/kubernetes/

tasks:  
  default:
    cmds:
      - task --list
