locals {
  module_path                             = "../.modules"
  resource_name                           = "${random_pet.this.id}-${random_id.this.dec}"
  aks_name                                = "${local.resource_name}-aks"
  apim_name                               = "${local.resource_name}-apim"
  vnet_name                               = "${local.resource_name}-vnet"
  workload_identity                       = "${local.resource_name}-app-identity"
  sa_name                                 = "${replace(local.resource_name, "-", "")}files"
  acr_name                                = "${replace(local.resource_name, "-", "")}acr"
  keyvault_name                           = "${replace(local.resource_name, "-", "")}akskv"
  app_keyvault_name                       = "${replace(local.resource_name, "-", "")}appkv"
  static_webapp_name                      = "${local.resource_name}-ui"
  sb_name                                 = "${local.resource_name}-pubsub"
  sql_name                                = "${local.resource_name}-sql"
  static_webapp_location                  = "centralus"
  openai_location                         = var.opeanai_region
  app_path                                = "./cluster-config"
  flux_repository                         = "https://github.com/briandenicola/dapr-ai-agents-demo"
  environment_type                        = "dev"
  vnet_cidr                               = cidrsubnet("10.0.0.0/8", 8, random_integer.vnet_cidr.result)
  pe_subnet_cidir                         = cidrsubnet(local.vnet_cidr, 8, 1)
  api_subnet_cidir                        = cidrsubnet(local.vnet_cidr, 8, 2)
  nodes_subnet_cidir                      = cidrsubnet(local.vnet_cidr, 8, 3)
  compute_subnet_cidir                    = cidrsubnet(local.vnet_cidr, 8, 4)
  sql_subnet_cidir                        = cidrsubnet(local.vnet_cidr, 8, 10)
  kubernetes_version                      = "1.32"
  istio_version                           = "asm-1-24"
  home_ip_address                         = chomp(data.http.myip.response_body)
  apim_backend_name                       = "${local.resource_name}-backend"
  apim_api_path                           = "api"
  app_apim_gateway_url                    = "${azurerm_api_management.this.gateway_url}/${local.apim_api_path}/analyze"
  otel_namespace                          = "otel-system"
  postgresql_user_name                    = "manager"
  postgresql_workflow_state_database_name = "workflowstatedb"
  postgresql_agent_state_database_name    = "agentstatedb"
  service_bus_secret_name                 = "sbconnection"
  azure_openai_secret_name                = "openaiapikey"   
  workflow_postgresql_secret_name         = "workflowsqlconnection"
  agent_postgresql_secret_name            = "agentsqlconnection"
}
