apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.KEYVAULT.SECRETS.AOAI }}
  namespace: {{ .Values.APP.NAMESPACE }}
spec:
  provider: azure
  secretObjects:
  - secretName: app-secrets
    type: Opaque                            
    data:                 
    - key: {{ .Values.KEYVAULT.SECRETS.AOAI }}
      objectName: {{ .Values.KEYVAULT.SECRETS.AOAI }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: {{ .Values.KEYVAULT.NAME }}
    clientID: {{ .Values.WORKLOAD_ID.CLIENT_ID }}
    cloudName: ""                                                  
    objects:  |
      array:
        - |
          objectName: {{ .Values.KEYVAULT.SECRETS.AOAI }}
          objectType: secret
          objectVersion: ""                               
    tenantId: {{ .Values.WORKLOAD_ID.TENANT_ID }}